# Generated by Django 3.1.7 on 2021-03-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlbstats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="anglesweetspotpercent",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="person",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="person",
            name="avg_distance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="person",
            name="avg_hit_angle",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="person",
            name="avg_hit_speed",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="person",
            name="avg_hr_distance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="person",
            name="barrels",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="person",
            name="brl_pa",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="person",
            name="brl_percent",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="person",
            name="ev95per_swing",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="person",
            name="ev95percent",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="person",
            name="ev95plus",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="person",
            name="fbld",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="person",
            name="first_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="person",
            name="gb",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="person",
            name="max_distance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="person",
            name="max_hit_speed",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="person",
            name="player_id",
            field=models.IntegerField(default=0),
        ),
    ]
