# Generated by Django 3.1.7 on 2021-03-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mlbstats", "0002_auto_20210321_1335"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Person",
            new_name="Player",
        ),
    ]
