# Generated by Django 3.1.7 on 2021-03-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlbstats", "0003_auto_20210321_1338"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="player",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
